# Pull image
FROM python:3.9.8-buster

# Env vars
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set workdir
WORKDIR /usr/src/luna_api

# Copy project
COPY ./docker/ ./docker
COPY ./api/ ./api
COPY ./alembic ./alembic
COPY ./poetry.lock .
COPY ./pyproject.toml .
COPY ./alembic.ini .

# Project dependencies
RUN apt update
RUN apt install curl
RUN python -m pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-dev

RUN chmod +x /usr/src/luna_api/docker/api/entrypoint.dev.sh

# Entrypoint
ENTRYPOINT ["/bin/sh", "/usr/src/luna_api/docker/api/entrypoint.dev.sh"]