services:
  database:
    image: postgres:15.2-alpine3.17
    container_name: database
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file: ./.env.production
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - luna_network

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    image: twylix/luna_api
    container_name: api
    restart: unless-stopped
    env_file: ./.env.production
    environment:
      - PRODUCTION=true
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/status/healthcheck"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - luna_network

  nginx:
    image: nginx:1.22-alpine
    container_name: nginx
    env_file: ./.env.production
    restart: on-failure:3
    volumes:
      - ./ssl/cert.crt:/etc/ssl/certs/cert.crt
      - ./ssl/private.key:/etc/ssl/private/private.key
      - ./docker/nginx/nginx.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 127.0.0.1:7080:80
      - 127.0.0.1:7443:443 # Uncomment this line if you want to use HTTPS
    networks:
      - luna_network

volumes:
  db_volume:


networks:
  luna_network:
    driver: bridge
    name: luna_network
