services:
  database:
    image: postgres:14.2
    container_name: database
    env_file: ./.env.dev
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    container_name: api
    volumes:
      - .:/usr/src/luna_api/
    env_file: ./.env.dev
    ports:
      - 8080:8000
    depends_on:
      database:
        condition: service_healthy
