version: "3.9"
services:
  db:
    image: postgres:14.2
    container_name: postgres
    volumes:
      - ./shared/postgres-data/:/var/lib/postgresql/data/
    env_file: ./.env.dev

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    container_name: api
    env_file: ./.env.prod
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    container_name: bot
    env_file: ./.env.prod
    depends_on:
      - api

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.prod
    container_name: nginx
    env_file: ./.env.prod
    depends_on:
      - bot
    ports:
      - 8080:80
      - 8443:443
