version: "3.9"
services:
  database:
    image: postgres:14.2
    container_name: database
    volumes:
      - ./shared/postgres-data-prod/:/var/lib/postgresql/data/
    env_file: ./.env.dev
    networks:
      - luna_network

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    container_name: api
    env_file: ./.env.prod
    depends_on:
      - database
    networks:
      - luna_network

  bot:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    container_name: bot
    env_file: ./.env.prod
    depends_on:
      - api
    networks:
      - luna_network

  nginx_backend:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.prod
    container_name: nginx_backend
    env_file: ./.env.prod
    depends_on:
      - bot
    ports:
      - 7080:80
      - 7443:443
    networks:
      - luna_network

networks:
  luna_network:
    driver: bridge
    name: luna_network
