version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    container_name: api
    volumes:
      - static_data:/var/www/luna.staypony.space/static
    env_file: ./.env.prod
    links:
      - db:db
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    container_name: bot
    env_file: ./.env.prod
    links:
      - db:db
    depends_on:
      - api

volumes:
  static_data:
