version: "3.9"
services:
  database:
    image: postgres:14.2
    container_name: database
    volumes:
      - ./shared/postgres-data-dev/:/var/lib/postgresql/data/
    env_file: ./.env.dev
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    container_name: api
    volumes:
      - .:/usr/src/luna_api/
    env_file: ./.env.dev
    ports:
      - 8080:8000
    links:
      - database:database
    depends_on:
      - database
